liip_imagine:
    driver: "gd"
    filter_sets:
        thumbnail_800x570:
            quality: 80
            filters:
                thumbnail:
                    size: [800, 570]
                    mode: outbound
                strip: ~

        standard_800x600:
            quality: 82
            filters:
                thumbnail:
                    size: [800, 600]
                    mode: outbound
                strip: ~

        square_400x400:
            quality: 82
            filters:
                thumbnail:
                    size: [400, 400]
                    mode: outbound
                strip: ~
        thumbnail_medium:
            quality: 80
            filters:
                thumbnail:
                    size: [600, 400]
                    mode: outbound
                strip: ~

        thumbnail_small:
            quality: 75
            filters:
                thumbnail:
                    size: [150, 150]
                    mode: outbound
                strip: ~
