vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: /uploads/products
            upload_destination: '%kernel.project_dir%/public/uploads/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        category_images:
            uri_prefix: /uploads/categories
            upload_destination: '%kernel.project_dir%/public/uploads/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        sub_category_images:
            uri_prefix: /uploads/sub_categories
            upload_destination: '%kernel.project_dir%/public/uploads/sub_categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        brand_images:
            uri_prefix: /uploads/brands
            upload_destination: '%kernel.project_dir%/public/uploads/brands'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
